# _config.yml

# Server Config

safe: true

source: ./src
destination: ./_site

timezone: Europe/London

future: false
lsi: false
pygments: false
markdown: rdiscount
rdiscount:
  extensions: [smart]

# Site Config

name: Birmingham Sports Awards 2014

url:
static: /static
media: /media

## Analytics

google_analytics_id:
